version: '3'

services: 
  api-soli-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=dockerpass
      - POSTGRESQL_DATABASE=apisolid